import { createHash } from "node:crypto";
import { createGitHubApi, type GitHubApi, type GitHubReviewEvent } from "./github-api.js";
import { logger } from "./utils/logger";
import { detectPlatform, parsePrUrl } from "./platform.js";
import { buildInlineComments } from "./inline-comments";
import { renderMarkdown, renderSummaryMarkdown } from "./render.js";
import type {
  ParsedPrUrl,
  PostCommentResult,
  ReviewFinding,
  ReviewOutput,
} from "./types.js";

export function getFindingFingerprint(
  finding: ReviewFinding,
): string {
  const path = finding.code_location.path;
  const title = finding.title.replace(/^\[P[0-3]\]\s*/, "").trim().toLowerCase();
  return createHash("sha256").update(`${path}\n${title}`).digest("hex");
}

/** GitLab publishing is intentionally unavailable in the Worker reviewer. */
export async function postGitlabReviewCommitStatus(
  _parsed: ParsedPrUrl,
  _review: ReviewOutput,
  _diffRefs: unknown,
): Promise<void> {
  throw new Error("Cloudflare Worker reviews currently support GitHub only");
}

export async function postReviewComment(opts: {
  prUrl: string;
  reviewText: string;
  githubToken?: string;
  githubApi?: GitHubApi;
  event?: GitHubReviewEvent;
  model?: string | null;
  metricsFooter?: string | null;
  headSha?: string | null;
  cacheMarker?: string | null;
}): Promise<PostCommentResult> {
  const {
    prUrl,
    reviewText,
    githubToken,
    githubApi: providedGitHubApi,
    event = "COMMENT",
    model,
    metricsFooter,
    headSha,
    cacheMarker,
  } = opts;
  const parsed = parsePrUrl(prUrl);
  const platform = detectPlatform(prUrl);
  if (platform !== "github") {
    return { success: false, platform, error: "Cloudflare Worker reviews currently support GitHub only" };
  }

  let body = reviewText;
  if (headSha) body = `<!-- hodor:sha:${headSha} -->\n${body}`;
  if (cacheMarker) body = body.replace("\n", `\n${cacheMarker}\n`);
  if (model) body += `\n---\n\nReview generated by Hodor (model: \`${model}\`)`;
  if (metricsFooter) body += `\n\n${metricsFooter}`;

  try {
    const githubApi = providedGitHubApi ?? createGitHubApi({ token: githubToken ?? "" });
    await githubApi.submitPullRequestReview(parsed.owner, parsed.repo, parsed.prNumber, {
      body,
      event,
      commitId: headSha ?? undefined,
    });
    return { success: true, platform, prNumber: parsed.prNumber };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    logger.error(`Failed to post GitHub review: ${message}`);
    return { success: false, platform, prNumber: parsed.prNumber, error: message };
  }
}

export async function postReviewStructured(opts: {
  prUrl: string;
  review: ReviewOutput;
  githubToken?: string;
  githubApi?: GitHubApi;
  event?: GitHubReviewEvent;
  model?: string | null;
  metricsFooter?: string | null;
  reviewStyle?: "summary" | "inline" | "hybrid";
  commitStatus?: boolean;
  headSha?: string | null;
  reconcileDiscussions?: boolean;
  cacheMarker?: string | null;
  skipSummary?: boolean;
}): Promise<PostCommentResult> {
  const {
    prUrl,
    review,
    githubToken,
    githubApi,
    event,
    model,
    metricsFooter,
    headSha,
    cacheMarker,
    skipSummary = false,
  } = opts;

  if (skipSummary) {
    return {
      success: false,
      platform: detectPlatform(prUrl),
      error: "GitHub Worker publishing requires a summary review",
    };
  }

  const parsed = parsePrUrl(prUrl);
  const platform = detectPlatform(prUrl);
  if (platform !== "github") {
    return { success: false, platform, error: "Cloudflare Worker reviews currently support GitHub only" };
  }

  try {
    const api = githubApi ?? createGitHubApi({ token: githubToken ?? "" });
    const diff = await api.getPullRequestDiff(parsed.owner, parsed.repo, parsed.prNumber);
    const inline = buildInlineComments(review, diff);
    let body = renderSummaryMarkdown(review);
    if (inline.skipped.length > 0) {
      body += renderUnplacedFindings(inline.skipped);
    }
    if (headSha) body = `<!-- hodor:sha:${headSha} -->\n${body}`;
    if (cacheMarker) body = body.replace("\n", `\n${cacheMarker}\n`);
    if (model) body += `\n---\n\nReview generated by Hodor (model: \`${model}\`)`;
    if (metricsFooter) body += `\n\n${metricsFooter}`;
    await api.submitPullRequestReview(parsed.owner, parsed.repo, parsed.prNumber, {
      body,
      event: event ?? (review.findings.length > 0 ? "REQUEST_CHANGES" : "APPROVE"),
      commitId: headSha ?? undefined,
      comments: inline.comments.length > 0 ? inline.comments : undefined,
    });
    return {
      success: true,
      platform,
      prNumber: parsed.prNumber,
      summaryPosted: true,
      inlineCreated: inline.comments.length,
      inlineFailed: inline.skipped.length,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    logger.error(`Failed to post GitHub review: ${message}`);
    return { success: false, platform, prNumber: parsed.prNumber, error: message };
  }
}

function renderUnplacedFindings(findings: ReviewFinding[]): string {
  const lines = ["", "### Findings without an inline location", ""];
  for (const finding of findings) {
    const location = finding.code_location;
    const range = location.line_range.start === location.line_range.end
      ? String(location.line_range.start)
      : `${location.line_range.start}-${location.line_range.end}`;
    lines.push(`- **${finding.title}** (\`${location.path}:${range}\`)`);
    lines.push(`  - ${finding.body}`);
  }
  return lines.join("\n");
}
